In [4]:
#Installation of the modules
!pip install pandas                              #for data analysis
!pip install numpy                               # numerical python consists of mathematical functions mean(), round() etc
!pip install matplotlib.pyplot as plt            #data visualization  to create basic level charts line, column, pie, etc
!pip install seaborn as sns                      #data visualization  to create advanced charts histogram, boxplots, heatmaps
!pip install datetime                            #for time series features

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
ERROR: Could not find a version that satisfies the requirement matplotlib.pyplot (from versions: none)
ERROR: No matching distribution found for matplotlib.pyplot
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (0.13.2)
ERROR: Could not find a version that satisfies the requirement as (from versions: none)
ERROR: No matching distribution found for as
Requirement already satisfied: datetime in /usr/local/lib/python3.12/dist-packages (6.0)
Requirement already satisfied: zope.interface in /usr/local/lib/python3.12/dist-packages (from datetime) (8.2)
Requirement already satisfied: pytz in /usr/local/lib/python3.12/dist-packages (from datetime) (2025.2)

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt

In [6]:
data = pd.read_csv("/content/claims.csv")
#pd.read_excel()

In [7]:
data.head()  #it shows only first five rows of data by default

,claim_id,customer_id,incident_cause,claim_date,claim_area,police_report,claim_type,claim_amount,total_policy_claims,fraudulent
0,54004764,21868593,Driver error,11/27/2017,Auto,No,Material only,$2980,1.0,No
1,33985796,75740424,Crime,10/03/2018,Home,Unknown,Material only,$2980,3.0,No
2,53522022,30308357,Other driver error,02/02/2018,Auto,No,Material only,$3369.5,1.0,Yes
3,13015401,47830476,Natural causes,06/17/2018,Auto,No,Material only,$1680,1.0,No
4,22890252,19269962,Crime,01/13/2018,Auto,No,Material only,$2680,1.0,No

In [8]:
#ESC+B : to add a new cell below
#ESC+A :  to add a new cell above
#ESC+X :  TO DELETE A CELL

In [9]:
data.columns

Index(['claim_id', 'customer_id', 'incident_cause', 'claim_date', 'claim_area',
       'police_report', 'claim_type', 'claim_amount', 'total_policy_claims',
       'fraudulent'],
      dtype='object')

In [10]:
loans = pd.read_csv("/content/LoansData (1).csv")

In [11]:
loans.head()

,LoanID,Amount.Requested,Amount.Funded.By.Investors,Interest.Rate,Loan.Length,Loan.Purpose,Debt.To.Income.Ratio,State,Home.Ownership,Monthly.Income,FICO.Range,Open.CREDIT.Lines,Revolving.CREDIT.Balance,Inquiries.in.the.Last.6.Months,Employment.Length
0,1,20000.0,20000.0,8.90%,36 months,debt_consolidation,14.90%,SC,MORTGAGE,6541.67,735-739,14.0,14272.0,2.0,< 1 year
1,2,19200.0,19200.0,12.12%,36 months,debt_consolidation,28.36%,TX,MORTGAGE,4583.33,715-719,12.0,11140.0,1.0,2 years
2,3,35000.0,35000.0,21.98%,60 months,debt_consolidation,23.81%,CA,MORTGAGE,11500.00,690-694,14.0,21977.0,1.0,2 years
3,4,10000.0,9975.0,9.99%,36 months,debt_consolidation,14.30%,KS,MORTGAGE,3833.33,695-699,10.0,9346.0,0.0,5 years
4,5,12000.0,12000.0,11.71%,36 months,credit_card,18.78%,NJ,RENT,3195.00,695-699,11.0,14469.0,0.0,9 years

In [12]:
loans.columns

Index(['LoanID', 'Amount.Requested', 'Amount.Funded.By.Investors',
       'Interest.Rate', 'Loan.Length', 'Loan.Purpose', 'Debt.To.Income.Ratio',
       'State', 'Home.Ownership', 'Monthly.Income', 'FICO.Range',
       'Open.CREDIT.Lines', 'Revolving.CREDIT.Balance',
       'Inquiries.in.the.Last.6.Months', 'Employment.Length'],
      dtype='object')

In [13]:
loans.columns = [col.replace('.', '_') for col in loans.columns]
display(loans.columns)

Index(['LoanID', 'Amount_Requested', 'Amount_Funded_By_Investors',
       'Interest_Rate', 'Loan_Length', 'Loan_Purpose', 'Debt_To_Income_Ratio',
       'State', 'Home_Ownership', 'Monthly_Income', 'FICO_Range',
       'Open_CREDIT_Lines', 'Revolving_CREDIT_Balance',
       'Inquiries_in_the_Last_6_Months', 'Employment_Length'],
      dtype='object')

In [14]:
loans.head()

,LoanID,Amount_Requested,Amount_Funded_By_Investors,Interest_Rate,Loan_Length,Loan_Purpose,Debt_To_Income_Ratio,State,Home_Ownership,Monthly_Income,FICO_Range,Open_CREDIT_Lines,Revolving_CREDIT_Balance,Inquiries_in_the_Last_6_Months,Employment_Length
0,1,20000.0,20000.0,8.90%,36 months,debt_consolidation,14.90%,SC,MORTGAGE,6541.67,735-739,14.0,14272.0,2.0,< 1 year
1,2,19200.0,19200.0,12.12%,36 months,debt_consolidation,28.36%,TX,MORTGAGE,4583.33,715-719,12.0,11140.0,1.0,2 years
2,3,35000.0,35000.0,21.98%,60 months,debt_consolidation,23.81%,CA,MORTGAGE,11500.00,690-694,14.0,21977.0,1.0,2 years
3,4,10000.0,9975.0,9.99%,36 months,debt_consolidation,14.30%,KS,MORTGAGE,3833.33,695-699,10.0,9346.0,0.0,5 years
4,5,12000.0,12000.0,11.71%,36 months,credit_card,18.78%,NJ,RENT,3195.00,695-699,11.0,14469.0,0.0,9 years

In [15]:
data.head(3)

,claim_id,customer_id,incident_cause,claim_date,claim_area,police_report,claim_type,claim_amount,total_policy_claims,fraudulent
0,54004764,21868593,Driver error,11/27/2017,Auto,No,Material only,$2980,1.0,No
1,33985796,75740424,Crime,10/03/2018,Home,Unknown,Material only,$2980,3.0,No
2,53522022,30308357,Other driver error,02/02/2018,Auto,No,Material only,$3369.5,1.0,Yes

In [16]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1100 entries, 0 to 1099
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   claim_id             1100 non-null   int64
 1   customer_id          1100 non-null   int64
 2   incident_cause       1100 non-null   object
 3   claim_date           1100 non-null   object
 4   claim_area           1100 non-null   object
 5   police_report        1100 non-null   object
 6   claim_type           1100 non-null   object
 7   claim_amount         1035 non-null   object
 8   total_policy_claims  1090 non-null   float64
 9   fraudulent           1100 non-null   object
dtypes: float64(1), int64(2), object(7)
memory usage: 86.1+ KB

In [17]:
data['claim_amount'] = data['claim_amount'].str.replace("$","").astype(float)

In [18]:
data.head()

,claim_id,customer_id,incident_cause,claim_date,claim_area,police_report,claim_type,claim_amount,total_policy_claims,fraudulent
0,54004764,21868593,Driver error,11/27/2017,Auto,No,Material only,2980.0,1.0,No
1,33985796,75740424,Crime,10/03/2018,Home,Unknown,Material only,2980.0,3.0,No
2,53522022,30308357,Other driver error,02/02/2018,Auto,No,Material only,3369.5,1.0,Yes
3,13015401,47830476,Natural causes,06/17/2018,Auto,No,Material only,1680.0,1.0,No
4,22890252,19269962,Crime,01/13/2018,Auto,No,Material only,2680.0,1.0,No

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1100 entries, 0 to 1099
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   claim_id             1100 non-null   int64
 1   customer_id          1100 non-null   int64
 2   incident_cause       1100 non-null   object
 3   claim_date           1100 non-null   object
 4   claim_area           1100 non-null   object
 5   police_report        1100 non-null   object
 6   claim_type           1100 non-null   object
 7   claim_amount         1035 non-null   float64
 8   total_policy_claims  1090 non-null   float64
 9   fraudulent           1100 non-null   object
dtypes: float64(2), int64(2), object(6)
memory usage: 86.1+ KB

In [20]:
loans.head()

,LoanID,Amount_Requested,Amount_Funded_By_Investors,Interest_Rate,Loan_Length,Loan_Purpose,Debt_To_Income_Ratio,State,Home_Ownership,Monthly_Income,FICO_Range,Open_CREDIT_Lines,Revolving_CREDIT_Balance,Inquiries_in_the_Last_6_Months,Employment_Length
0,1,20000.0,20000.0,8.90%,36 months,debt_consolidation,14.90%,SC,MORTGAGE,6541.67,735-739,14.0,14272.0,2.0,< 1 year
1,2,19200.0,19200.0,12.12%,36 months,debt_consolidation,28.36%,TX,MORTGAGE,4583.33,715-719,12.0,11140.0,1.0,2 years
2,3,35000.0,35000.0,21.98%,60 months,debt_consolidation,23.81%,CA,MORTGAGE,11500.00,690-694,14.0,21977.0,1.0,2 years
3,4,10000.0,9975.0,9.99%,36 months,debt_consolidation,14.30%,KS,MORTGAGE,3833.33,695-699,10.0,9346.0,0.0,5 years
4,5,12000.0,12000.0,11.71%,36 months,credit_card,18.78%,NJ,RENT,3195.00,695-699,11.0,14469.0,0.0,9 years

In [21]:
l1 = loans.copy()

In [22]:
l1['FICO_Range'] = l1['FICO_Range'].str.split('-').str[0].astype(float)

In [23]:
loans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 15 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   LoanID                          2500 non-null   int64
 1   Amount_Requested                2499 non-null   float64
 2   Amount_Funded_By_Investors      2499 non-null   float64
 3   Interest_Rate                   2498 non-null   object
 4   Loan_Length                     2500 non-null   object
 5   Loan_Purpose                    2500 non-null   object
 6   Debt_To_Income_Ratio            2499 non-null   object
 7   State                           2500 non-null   object
 8   Home_Ownership                  2499 non-null   object
 9   Monthly_Income                  2499 non-null   float64
 10  FICO_Range                      2498 non-null   object
 11  Open_CREDIT_Lines               2497 non-null   float64
 12  Revolving_CREDIT_Balance        2497 non-null   float64
 13  Inquiries_in_the_Last_6_Months  2497 non-null   float64
 14  Employment_Length               2423 non-null   object
dtypes: float64(6), int64(1), object(8)
memory usage: 293.1+ KB

In [24]:
l1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 15 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   LoanID                          2500 non-null   int64
 1   Amount_Requested                2499 non-null   float64
 2   Amount_Funded_By_Investors      2499 non-null   float64
 3   Interest_Rate                   2498 non-null   object
 4   Loan_Length                     2500 non-null   object
 5   Loan_Purpose                    2500 non-null   object
 6   Debt_To_Income_Ratio            2499 non-null   object
 7   State                           2500 non-null   object
 8   Home_Ownership                  2499 non-null   object
 9   Monthly_Income                  2499 non-null   float64
 10  FICO_Range                      2498 non-null   float64
 11  Open_CREDIT_Lines               2497 non-null   float64
 12  Revolving_CREDIT_Balance        2497 non-null   float64
 13  Inquiries_in_the_Last_6_Months  2497 non-null   float64
 14  Employment_Length               2423 non-null   object
dtypes: float64(7), int64(1), object(7)
memory usage: 293.1+ KB

In [25]:
l1 = l1.rename(columns = {'FICO_Range':'FICO_SCORE'})

In [26]:
l1.head()

,LoanID,Amount_Requested,Amount_Funded_By_Investors,Interest_Rate,Loan_Length,Loan_Purpose,Debt_To_Income_Ratio,State,Home_Ownership,Monthly_Income,FICO_SCORE,Open_CREDIT_Lines,Revolving_CREDIT_Balance,Inquiries_in_the_Last_6_Months,Employment_Length
0,1,20000.0,20000.0,8.90%,36 months,debt_consolidation,14.90%,SC,MORTGAGE,6541.67,735.0,14.0,14272.0,2.0,< 1 year
1,2,19200.0,19200.0,12.12%,36 months,debt_consolidation,28.36%,TX,MORTGAGE,4583.33,715.0,12.0,11140.0,1.0,2 years
2,3,35000.0,35000.0,21.98%,60 months,debt_consolidation,23.81%,CA,MORTGAGE,11500.00,690.0,14.0,21977.0,1.0,2 years
3,4,10000.0,9975.0,9.99%,36 months,debt_consolidation,14.30%,KS,MORTGAGE,3833.33,695.0,10.0,9346.0,0.0,5 years
4,5,12000.0,12000.0,11.71%,36 months,credit_card,18.78%,NJ,RENT,3195.00,695.0,11.0,14469.0,0.0,9 years

In [27]:
l1['Interest_Rate'] = l1['Interest_Rate'].str.replace('%', '').astype(float)
l1['Loan_Length'] = l1['Loan_Length'].str.replace(' months', '').astype(float)
l1['Debt_To_Income_Ratio'] = l1['Debt_To_Income_Ratio'].str.replace('%', '').astype(float)

In [28]:
def clean_employment_length(length):
    if pd.isna(length):
        return np.nan
    length = str(length).lower()
    if 'year' in length:
        if '< 1' in length:
            return 0.0
        elif '10+' in length:
            return 10.0
        else:
            return float(length.replace(' years', '').replace(' year', ''))
    return np.nan

l1['Employment_Length'] = l1['Employment_Length'].apply(clean_employment_length).astype(float)

In [29]:
l1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 15 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   LoanID                          2500 non-null   int64
 1   Amount_Requested                2499 non-null   float64
 2   Amount_Funded_By_Investors      2499 non-null   float64
 3   Interest_Rate                   2498 non-null   float64
 4   Loan_Length                     2500 non-null   float64
 5   Loan_Purpose                    2500 non-null   object
 6   Debt_To_Income_Ratio            2499 non-null   float64
 7   State                           2500 non-null   object
 8   Home_Ownership                  2499 non-null   object
 9   Monthly_Income                  2499 non-null   float64
 10  FICO_SCORE                      2498 non-null   float64
 11  Open_CREDIT_Lines               2497 non-null   float64
 12  Revolving_CREDIT_Balance        2497 non-null   float64
 13  Inquiries_in_the_Last_6_Months  2497 non-null   float64
 14  Employment_Length               2423 non-null   float64
dtypes: float64(11), int64(1), object(3)
memory usage: 293.1+ KB

In [30]:
l1.head()

,LoanID,Amount_Requested,Amount_Funded_By_Investors,Interest_Rate,Loan_Length,Loan_Purpose,Debt_To_Income_Ratio,State,Home_Ownership,Monthly_Income,FICO_SCORE,Open_CREDIT_Lines,Revolving_CREDIT_Balance,Inquiries_in_the_Last_6_Months,Employment_Length
0,1,20000.0,20000.0,8.90,36.0,debt_consolidation,14.90,SC,MORTGAGE,6541.67,735.0,14.0,14272.0,2.0,0.0
1,2,19200.0,19200.0,12.12,36.0,debt_consolidation,28.36,TX,MORTGAGE,4583.33,715.0,12.0,11140.0,1.0,2.0
2,3,35000.0,35000.0,21.98,60.0,debt_consolidation,23.81,CA,MORTGAGE,11500.00,690.0,14.0,21977.0,1.0,2.0
3,4,10000.0,9975.0,9.99,36.0,debt_consolidation,14.30,KS,MORTGAGE,3833.33,695.0,10.0,9346.0,0.0,5.0
4,5,12000.0,12000.0,11.71,36.0,credit_card,18.78,NJ,RENT,3195.00,695.0,11.0,14469.0,0.0,9.0

In [31]:
data.isnull().sum()

claim_id                0
customer_id             0
incident_cause          0
claim_date              0
claim_area              0
police_report           0
claim_type              0
claim_amount           65
total_policy_claims    10
fraudulent              0
dtype: int64

In [34]:
#loans.isna().sum()

In [33]:
data['claim_amount']

0        2980.0
1        2980.0
2        3369.5
3        1680.0
4        2680.0
         ...
1095     3059.0
1096     1520.0
1097    23575.0
1098    25120.0
1099    36685.0
Name: claim_amount, Length: 1100, dtype: float64

In [ ]:
'''
median_claim_amount = data['claim_amount'].median()
data['claim_amount'].fillna(median_claim_amount, inplace=True)
display(data['claim_amount'].isnull().sum())
'''

In [35]:
data['claim_amount'] = data['claim_amount'].fillna(data['claim_amount'].median())

In [36]:
data.isnull().sum()

claim_id                0
customer_id             0
incident_cause          0
claim_date              0
claim_area              0
police_report           0
claim_type              0
claim_amount            0
total_policy_claims    10
fraudulent              0
dtype: int64